
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import tkinter.font as font

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\acolajes\Dropbox\My PC (LAJES003)\Downloads\build\build\assets\frame0")





def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x680")
window.configure(bg = "#004A8B")


canvas = Canvas(
    window,
    bg = "#004A8B",
    height = 680,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    658.0,
    32.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    658.0,
    97.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    145.0,
    383.0,
    image=image_image_3
)


def checkb():

    if vareps_quarenta.get()==1:
        eps_trinta_cb.config(state='disabled')
    else:
        eps_trinta_cb.config(state='normal')

    if vareps_trinta.get()==1:
        eps_quarenta_cb.config(state='disabled')
    else:
        eps_quarenta_cb.config(state='normal')


vareps_trinta=IntVar(window)
eps_trinta_cb= Checkbutton(text='30CM',variable=vareps_trinta,onvalue=1,offvalue=0,disabledforeground="gray",background='white',command=checkb)
eps_trinta_cb.place(x=120,y=298)


vareps_quarenta=IntVar(window)
eps_quarenta_cb= Checkbutton(text='40CM',variable=vareps_quarenta,onvalue=1,offvalue=0,disabledforeground="gray",background='white',command=checkb)
eps_quarenta_cb.place(x=195,y=298)





# -----------------------------------

def trelica():
    if h8.get()==1:
        h12_cb.config(state='disabled')
        h12_cb.deselect()
        h16_cb.config(state='disabled')
        h16_cb.deselect()
        h20_cb.config(state='disabled')
        h20_cb.deselect()
        h25_cb.config(state='disabled')
        h25_cb.deselect()
    
    elif h12.get()==1:
        h8_cb.config(state='disabled')
        h8_cb.deselect()
        h16_cb.config(state='disabled')
        h16_cb.deselect()
        h20_cb.config(state='disabled')
        h20_cb.deselect()
        h25_cb.config(state='disabled')
        h25_cb.deselect()
    elif h16.get()==1:
        h8_cb.config(state='disabled')
        h8_cb.deselect()
        h12_cb.config(state='disabled')
        h12_cb.deselect()
        h20_cb.config(state='disabled')
        h20_cb.deselect()
        h25_cb.config(state='disabled')
        h25_cb.deselect()
    elif h20.get()==1:
        h8_cb.config(state='disabled')
        h8_cb.deselect()
        h12_cb.config(state='disabled')
        h12_cb.deselect()
        h16_cb.config(state='disabled')
        h16_cb.deselect()
        h25_cb.config(state='disabled')
        h25_cb.deselect()
    elif h25.get()==1:
        h8_cb.config(state='disabled')
        h8_cb.deselect()
        h12_cb.config(state='disabled')
        h12_cb.deselect()
        h16_cb.config(state='disabled')
        h16_cb.deselect()
        h20_cb.config(state='disabled')
        h20_cb.deselect()
    else:
        h8_cb.config(state='normal')
        h12_cb.config(state='normal')
        h16_cb.config(state='normal')
        h20_cb.config(state='normal')
        h25_cb.config(state='normal')

h8=IntVar()
h8_cb= Checkbutton(state='normal',variable=h8,onvalue=1,offvalue=0,background='white',disabledforeground="gray",command=trelica)
h8_cb.place(x=18,y=220)

h12=IntVar()
h12_cb= Checkbutton(state='normal',variable=h12,onvalue=1,offvalue=0,background='white',disabledforeground="gray",command=trelica)
h12_cb.place(x=55,y=220)

h16=IntVar()
h16_cb= Checkbutton(state='normal',variable=h16,onvalue=1,offvalue=0,background='white',disabledforeground="gray",command=trelica)
h16_cb.place(x=105,y=220)

h20=IntVar()
h20_cb= Checkbutton(state='normal',variable=h20,onvalue=1,offvalue=0,background='white',disabledforeground="gray",command=trelica)
h20_cb.place(x=160,y=220)

h25=IntVar()
h25_cb= Checkbutton(state='normal',variable=h25,onvalue=1,offvalue=0,background='white',disabledforeground="gray",command=trelica)
h25_cb.place(x=225,y=220)




image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    1064.0,
    382.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    617.0,
    383.0,
    image=image_image_12
)

image_image_13 = PhotoImage(
    file=relative_to_assets("image_13.png"))
image_13 = canvas.create_image(
    613.0,
    234.0,
    image=image_image_13
)

image_image_14 = PhotoImage(
    file=relative_to_assets("image_14.png"))
image_14 = canvas.create_image(
    613.0,
    395.0,
    image=image_image_14
)

image_image_15 = PhotoImage(
    file=relative_to_assets("image_15.png"))
image_15 = canvas.create_image(
    407.0,
    546.0,
    image=image_image_15
)

image_image_16 = PhotoImage(
    file=relative_to_assets("image_16.png"))
image_16 = canvas.create_image(
    613.0,
    546.0,
    image=image_image_16
)

image_image_17 = PhotoImage(
    file=relative_to_assets("image_17.png"))
image_17 = canvas.create_image(
    819.0,
    546.0,
    image=image_image_17
)

image_image_18 = PhotoImage(
    file=relative_to_assets("image_18.png"))
image_18 = canvas.create_image(
    1065.0,
    386.0,
    image=image_image_18
)

image_image_19 = PhotoImage(
    file=relative_to_assets("image_19.png"))
image_19 = canvas.create_image(
    738.0,
    652.0,
    image=image_image_19
)

image_image_20 = PhotoImage(
    file=relative_to_assets("image_20.png"))
image_20 = canvas.create_image(
    145.0,
    654.0,
    image=image_image_20
)

canvas.create_text(
    179.0,
    18.0,
    anchor="nw",
    text="CALCULADORA DE LAJE TRELIÇADA",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    149.0,
    69.0,
    anchor="nw",
    text="Cliente:",
    fill="#000000",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    145.0,
    103.0,
    anchor="nw",
    text="Endereço:",
    fill="#000000",
    font=("Inter", 20 * -1)
)


nome_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
nome_entry.place(
    x=225.0,
    y=72.0,
    width=378.0,
    height=20.0
)


endereco_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
endereco_entry.place(
    x=264.0,
    y=100.0,
    width=895.0,
    height=22.0
)

canvas.create_text(
    625.0,
    70.0,
    anchor="nw",
    text="CPF:",
    fill="#000000",
    font=("Inter", 20 * -1)
)


cpf_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
cpf_entry.place(
    x=682.0,
    y=72.0,
    width=197.0,
    height=20.0
)

canvas.create_text(
    890.0,
    70.0,
    anchor="nw",
    text="Tel.:",
    fill="#000000",
    font=("Inter", 20 * -1)
)


telefone_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
telefone_entry.place(
    x=937.0,
    y=72.0,
    width=222.0,
    height=20.0
)

image_image_21 = PhotoImage(
    file=relative_to_assets("image_21.png"))
image_21 = canvas.create_image(
    71.0,
    369.0,
    image=image_image_21
)

canvas.create_text(
    156.0,
    329.0,
    anchor="nw",
    text="LARGURA\n(quantidade de vigas)",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    158.0,
    425.0,
    anchor="nw",
    text="COMPRIMENTO",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    20.0,
    152.0,
    anchor="nw",
    text="ALTURA  DA TRELIÇA",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)


vigas_entry=Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
vigas_entry.place(
    x=160.0,
    y=362.0,
    width=61.0,
    height=19.0
)

canvas.create_text(
    226.0,
    365.0,
    anchor="nw",
    text="METROS",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)


vigas_quantidade_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
vigas_quantidade_entry.place(
    x=160.0,
    y=387.0,
    width=61.0,
    height=18.0
)

canvas.create_text(
    226.0,
    392.0,
    anchor="nw",
    text="VIGAS",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    45.0,
    397.0,
    anchor="nw",
    text="MENOS 1 VIGA",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)


tamanho_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
tamanho_entry.place(
    x=160.0,
    y=450.0,
    width=61.0,
    height=18.0
)

canvas.create_text(
    223.0,
    455.0,
    anchor="nw",
    text="METROS",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_rectangle(
    17.366424560546875,
    412.1398787498474,
    271.6487579345703,
    416.1172180175781,
    fill="#FFF400",
    outline="")

canvas.create_rectangle(
    17.366424560546875,
    326.7780303955078,
    271.6487579345703,
    330.75537109375,
    fill="#FFF400",
    outline="")

canvas.create_rectangle(
    17.366424560546875,
    486.3995819091797,
    271.6487579345703,
    490.3769226074219,
    fill="#FFF400",
    outline="")

image_image_22 = PhotoImage(
    file=relative_to_assets("image_22.png"))
image_22 = canvas.create_image(
    87.0,
    449.0,
    image=image_image_22
)

image_image_23 = PhotoImage(
    file=relative_to_assets("image_23.png"))
image_23 = canvas.create_image(
    31.0,
    191.0,
    image=image_image_23
)

image_image_24 = PhotoImage(
    file=relative_to_assets("image_24.png"))
image_24 = canvas.create_image(
    116.0,
    185.0,
    image=image_image_24
)

image_image_25 = PhotoImage(
    file=relative_to_assets("image_25.png"))
image_25 = canvas.create_image(
    174.0,
    183.0,
    image=image_image_25
)

image_image_26 = PhotoImage(
    file=relative_to_assets("image_26.png"))
image_26 = canvas.create_image(
    238.0,
    181.0,
    image=image_image_26
)

image_image_27 = PhotoImage(
    file=relative_to_assets("image_27.png"))
image_27 = canvas.create_image(
    66.0,
    188.0,
    image=image_image_27
)

canvas.create_text(
    23.0,
    208.0,
    anchor="nw",
    text="H8",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    58.0,
    208.0,
    anchor="nw",
    text="H12",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    105.0,
    208.0,
    anchor="nw",
    text="H16",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    161.0,
    208.0,
    anchor="nw",
    text="H20",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    226.0,
    208.0,
    anchor="nw",
    text="H25",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)



image_image_29 = PhotoImage(
    file=relative_to_assets("image_29.png"))
image_29 = canvas.create_image(
    222.0,
    274.0,
    image=image_image_29
)

image_image_30 = PhotoImage(
    file=relative_to_assets("image_30.png"))
image_30 = canvas.create_image(
    147.0,
    270.0,
    image=image_image_30
)

# canvas.create_text(
#     136.0,
#     291.0,
#     anchor="nw",
#     text="30CM",
#     fill="#000000",
#     font=("Inter Bold", 10 * -1)
# )

canvas.create_text(
    25.0,
    266.0,
    anchor="nw",
    text="LARGURA \n     DO \nPREENCHIMENTO",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

# canvas.create_text(
#     196.0,
#     291.0,
#     anchor="nw",
#     text="40CM",
#     fill="#000000",
#     font=("Inter Bold", 10 * -1)
# )

canvas.create_text(
    28.0,
    491.0,
    anchor="nw",
    text="AÇO ADICIONAL(REFORÇO):",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    22.0,
    505.0,
    anchor="nw",
    text="(informar quantidade de barras)",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

image_image_31 = PhotoImage(
    file=relative_to_assets("image_31.png"))
image_31 = canvas.create_image(
    220.0,
    575.0,
    image=image_image_31
)

canvas.create_text(
    30.0,
    520.0,
    anchor="nw",
    text="5mm = ",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    30.0,
    537.0,
    anchor="nw",
    text="6mm =",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    30.0,
    553.0,
    anchor="nw",
    text="8mm = ",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    28.0,
    568.0,
    anchor="nw",
    text="10mm = ",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    28.0,
    583.0,
    anchor="nw",
    text="12mm = ",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)

canvas.create_text(
    28.0,
    599.0,
    anchor="nw",
    text="16mm = ",
    fill="#000000",
    font=("Inter Bold", 10 * -1)
)


cinco_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
cinco_mm_entry.place(
    x=71.0,
    y=522.0,
    width=30.0,
    height=11.0
)


seis_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
seis_mm_entry.place(
    x=71.0,
    y=538.0,
    width=30.0,
    height=11.0
)


oito_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
oito_mm_entry.place(
    x=71.0,
    y=554.0,
    width=30.0,
    height=11.0
)


dez_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
dez_mm_entry.place(
    x=71.0,
    y=569.0,
    width=30.0,
    height=11.0
)


doze_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
doze_mm_entry.place(
    x=71.0,
    y=585.0,
    width=30.0,
    height=11.0
)


dezesseis_mm_entry = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
dezesseis_mm_entry.place(
    x=71.0,
    y=600.0,
    width=30.0,
    height=11.0
)

bt_adicionar_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
bt_adicionar = Button(
    image=bt_adicionar_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
bt_adicionar.place(
    x=53.80316162109375,
    y=639.84716796875,
    width=182.38223266601562,
    height=28.847259521484375
)

bt_apaga_u_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
bt_apaga_u = Button(
    image=bt_apaga_u_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
bt_apaga_u.place(
    x=322.08612060546875,
    y=638.0253295898438,
    width=162.62486267089844,
    height=28.847259521484375
)

bt_calc_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
bt_calc = Button(
    image=bt_calc_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
bt_calc.place(
    x=514.6905517578125,
    y=638.0253295898438,
    width=235.09896850585938,
    height=28.847259521484375
)

bt_save_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
bt_save = Button(
    image=bt_save_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
bt_save.place(
    x=781.5368041992188,
    y=638.0253295898438,
    width=171.46316528320312,
    height=28.847259521484375
)

bt_recarregar_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
bt_recarregar= Button(
    image=bt_recarregar_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
bt_recarregar.place(
    x=980.0,
    y=637.9197387695312,
    width=171.463134765625,
    height=28.847259521484375
)

image_image_32 = PhotoImage(
    file=relative_to_assets("image_32.png"))
image_32 = canvas.create_image(
    70.0,
    69.0,
    image=image_image_32
)

canvas.create_text(
    863.0,
    162.0,
    anchor="nw",
    text="H8",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    860.0,
    319.0,
    anchor="nw",
    text="H12",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    470.0,
    481.0,
    anchor="nw",
    text="H16",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    676.0,
    481.0,
    anchor="nw",
    text="H20",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    882.0,
    481.0,
    anchor="nw",
    text="H25",
    fill="#000000",
    font=("Inter Bold", 14 * -1)
)
window.resizable(False, False)
window.mainloop()
